name: emgbench
channels:
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - appdirs=1.4.4
  - asciitree=0.3.3
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=23.2.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blinker=1.7.0
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.26.0
  - c-blosc2=2.14.4
  - ca-certificates=2024.6.2
  - cachetools=5.3.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.1
  - cryptography=42.0.5
  - cuda-version=11.2
  - cudatoolkit=11.2.72
  - cudnn=8.8.0.121
  - dataclasses=0.8
  - decorator=5.1.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - executing=2.0.1
  - fasteners=0.17.3
  - filelock=3.13.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - gdown=5.2.0
  - gitdb=4.0.11
  - gitpython=3.1.40
  - google-auth=2.27.0
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib-resources=6.1.1
  - importlib_resources=6.1.1
  - ipython=8.18.1
  - jedi=0.19.1
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.21.2
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.7.1
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libprotobuf=3.21.8
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.4.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.11.6
  - libzlib=1.2.13
  - lightning-utilities=0.10.1
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - magma=2.5.4
  - markdown=3.5.2
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.6
  - mkl=2022.2.1
  - msgpack-python=1.0.7
  - multidict=6.0.5
  - munkres=1.1.4
  - nccl=2.21.5.1
  - ncurses=6.4.20240210
  - ninja=1.11.1
  - numcodecs=0.12.1
  - numexpr=2.7.3
  - numpy=1.26.4
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.3.1
  - packaging=24.0
  - parso=0.8.3
  - pathtools=0.1.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.2
  - platformdirs=4.2.0
  - pooch=1.8.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pygments=2.18.0
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - pytables=3.9.2
  - python=3.9.19
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch-lightning=1.9.4
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - safetensors=0.4.3
  - sentry-sdk=1.39.1
  - setproctitle=1.3.3
  - setuptools=68.2.2
  - six=1.16.0
  - sleef=3.5.1
  - smmap=5.0.0
  - snappy=1.2.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.11.0
  - tensorboard-plugin-wit=1.8.1
  - timm=0.9.12
  - tk=8.6.13
  - torchmetrics=0.11.4
  - traitlets=5.14.3
  - typing=3.10.0.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - unicodedata2=15.1.0
  - wandb=0.16.1
  - wcwidth=0.2.13
  - webcolors=1.13
  - werkzeug=3.0.1
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zarr=2.15.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - aim==3.19.3
      - aim-ui==3.19.3
      - aimrecords==0.0.7
      - aimrocks==0.4.0
      - aiofiles==23.2.1
      - alembic==1.13.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - base58==2.0.1
      - boto3==1.34.92
      - botocore==1.34.92
      - certifi==2024.2.2
      - cycler==0.12.1
      - dcor==0.6
      - emd==0.7.0
      - exceptiongroup==1.2.1
      - fastapi==0.110.2
      - fcwt==0.1.18
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - greenlet==3.0.3
      - grpcio==1.62.2
      - h11==0.14.0
      - h5py==3.11.0
      - huggingface-hub==0.22.2
      - imageio==2.34.1
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.4.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - llvmlite==0.42.0
      - mako==1.3.3
      - matplotlib==3.8.4
      - mpmath==1.3.0
      - networkx==3.2.1
      - numba==0.59.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.2.2
      - pillow==10.3.0
      - progress==1.6
      - protobuf==4.25.3
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pytz==2024.1
      - regex==2024.4.16
      - restrictedpython==7.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - s3transfer==0.10.1
      - scikit-image==0.22.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - semilearn==0.3.2
      - sniffio==1.3.1
      - sparse==0.15.1
      - sqlalchemy==2.0.29
      - starlette==0.37.2
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.4.0
      - tifffile==2024.4.24
      - tokenizers==0.19.1
      - torch==2.3.0
      - torchaudio==2.3.0
      - torchvision==0.18.0
      - tqdm==4.66.2
      - transformers==4.40.1
      - triton==2.3.0
      - tzdata==2024.1
      - urllib3==1.26.18
      - uvicorn==0.29.0
      - websockets==12.0
prefix: /home/emgbench-test/miniforge3/envs/emgbench
